version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000' 
    environment:
      - NODE_ENV=development
      - MONG_URI=#

  frontend:
    build:
      context: ./client/prayerapp
      dockerfile: Dockerfile
    ports:
      - '3000:3000' 
    environment:
      - NODE_ENV=development
    depends_on:
      - backend